language: java
jdk: oraclejdk8
os: linux
sudo: required
dist: trusty
notifications:
  email: false
# addons:
#   apt:
#     packages:
#       - oracle-java8-installer
env:
- IS_BAMBOO=true
install:
- ./gradlew assemble
script:
# - ./gradlew --no-daemon --info generateTestSuites
- ./gradlew --no-daemon --info test -PisTravisCI=true
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
